services:
  web:
    image: php:8.3-apache
    container_name: apache-php
    ports:
      - "8090:80"
    volumes:
      - ./html:/var/www/html
      - ./config/php:/usr/local/etc/php
      - ./logs:/var/log/
      - ./config/apache2:/etc/apache2/sites-enabled
    networks:
      - flapp-network
    build:
      context: .
      dockerfile: Dockerfile
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flapp
    volumes:
      - db_data:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - flapp-network
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - flapp-network
networks:
  flapp-network:
    driver: bridge

volumes:
  db_data:
